### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by AwesomeAustn**
## Checklist

- [X] I only edited my own config files.
- [X] I didn't upload any poster or background images to the repository

### CODE REVIEW

**Comment by YozoraXCII** [comment]
Whats going on with this PR? 450+ commits lol

**Comment by AwesomeAustn** [comment]
I have no idea. I just did a big update a little bit ago. Maybe it's doing it over again.

**Comment by cpt-kuesel** [comment]
Please look into pulling the current repo into yours before the next pull request.

**Comment by AwesomeAustn** [comment]
I use GitHub Desktop. So Pull and then Push?

**Comment by cpt-kuesel** [comment]
Yeah, the order should be:
- fetch from the meisnate repo into your own on github
- then pull your own github repo into your local
- make your changes local
- then push to your github repo
- open the pull request from your github repo to the meisnate repo

**Comment by AwesomeAustn** [comment]
So I just fetched on GitHub Desktop and now it says I have a Push for 458 local commits.

**Comment by AwesomeAustn** [comment]
This is just a pain for me. I want to just remove my folder. Do I just delete my folder and then do a Push?

**Comment by cpt-kuesel** [comment]
before it was a pain for us to merge your 450 commits every time you made changes.

sure you can remove your folder if it really is too much of a hassle.

**Comment by AwesomeAustn** [comment]
I didn't make any changes this time and it still says 458. I just don't understand how this works.

**Comment by AwesomeAustn** [comment]
I deleted my fork. Can you please remove my folder?

**Comment by cpt-kuesel** [comment]
basically there are three locations.
local on your pc, your own fork of the repo and the original repo.
you make local changes push them to your fork and pull request them into the original repo.
the original repo accepts changes from other users and so your own fork gets old and your local versions as well.
to refresh you first fetch all new stuff from the original repo in your fork and after that you can pull the changes from your fork into your local version.
this should clear up the number of your outstanding local commits before making new changes

**Comment by cpt-kuesel** [comment]
okay will do

**Comment by AwesomeAustn** [comment]
Thank you!

**Comment by SaintNick1214** [comment]
AwesomeAustn you had the best configs, wth man  :(

**Comment by AwesomeAustn** [comment]
Thanks! I appreciate it!

GitHub just wasn't working out for me. Somehow I didn't have the latest updates when GitHub Desktop said it was up to date, and then I somehow keep pushing to the wrong branch, and GitHub Desktop kept saying I had hundreds of commits even after they went through.

I still have them all on my MEGA folder here:
linkr.ee/awesomeaustn

**Pull request merged**
