### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by AwesomeAustn**
## Checklist

- [x] I only edited my own config files
- [x] I didn't upload any poster or background images to the repository

### CODE REVIEW

**Comment by YozoraXCII** [comment]
A few issues here.
- you have 400+ commits
- you are editing other people's files, such as:
   Frexe/Movies/Collections/Movie Collection.yml
   AwesomeAustn/Movies - Holidays by Drazzizzi.yml
   you are also editing files within the .github folder

**Comment by AwesomeAustn** [comment]
Ok. Please remove my folder then. I don't want to have my old stuff there.

**Comment by meisnate12** [comment]
ok i fixed the branches

**Comment by AwesomeAustn** [comment]
Thanks

**Pull request merged**
